version: "3.8"
services:
  postgresql:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=senha
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"

  redis:
    image: redis:latest
    ports:
      - "6380:6379"      

  web:
    build: .
    ports:
      - "3002:3000"
    depends_on:
      - postgresql
      - redis
    environment: 
      - DATABASE_URL=postgres://postgres:senha@postgresql:5432/postgres
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app

volumes:
  dbdata:
  