name: Build-Image

on:
  push:
    branches:
      - 'master'

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login build and push Docker image
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: jesherpinkman/socialm
          dockerfile: Dockerfile
          tags: latest