name: Build-Image

on:
  push:
    branches:
      - 'master'

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          run: docker build . --file Dockerfile --tag jesherpinkman/socialm
          context: .
          push: true
          tags: jesherpinkman/socialm:latest